INSERT INTO books (title, series_id, publication_date) VALUES ('The Way of Kings', 1, '2010-08-31');
INSERT INTO books (title, series_id, publication_date) VALUES ('Words of Radiance', 1, '2014-03-04');
INSERT INTO books (title, series_id, publication_date) VALUES ('Edgedancer', 1, '2016-11-22');
INSERT INTO books (title, series_id, publication_date) VALUES ('Oathbringer', 1, '2017-11-14');
INSERT INTO books (title, series_id, publication_date) VALUES ('Dawnshard', 1, '2020-11-05');
INSERT INTO books (title, series_id, publication_date) VALUES ('Rhythm of War', 1, '2020-11-17');
INSERT INTO books (title, series_id, publication_date) VALUES ('Wind and Truth', 1, '2024-12-06');
INSERT INTO books (title, series_id, publication_date) VALUES ('Mistborn: The Final Empire', 2, '2006-07-17');
INSERT INTO books (title, series_id, publication_date) VALUES ('The Well of Ascension', 2, '2007-08-21');
INSERT INTO books (title, series_id, publication_date) VALUES ('The Hero of Ages', 2, '2008-10-14');
INSERT INTO books (title, series_id, publication_date) VALUES ('The Alloy of Law', 3, '2011-11-08');
INSERT INTO books (title, series_id, publication_date) VALUES ('Shadows of Self', 3, '2015-10-06');
INSERT INTO books (title, series_id, publication_date) VALUES ('The Bands of Mourning', 3, '2016-01-26');
INSERT INTO books (title, series_id, publication_date) VALUES ('The Lost Metal', 3, '2022-11-15');
INSERT INTO books (title, series_id, publication_date) VALUES ('Mistborn: Secret History', 4, '2016-01-26');
INSERT INTO books (title, series_id, publication_date) VALUES ('The Eleventh Metal', 4, '2011-12-15');
INSERT INTO books (title, series_id, publication_date) VALUES ('Allomancer Jak and the Pits of Eltania', 4, '2014-08-07');
INSERT INTO books (title, series_id, publication_date) VALUES ('Arcanum Unbounded', 4, '2016-11-22');
INSERT INTO books (title, series_id, publication_date) VALUES ('Elantris', 4, '2005-04-21');
INSERT INTO books (title, series_id, publication_date) VALUES ('Isles of the Emberdark', 4, '2025-07-01');
INSERT INTO books (title, series_id, publication_date) VALUES ('The Sunlit Man', 4, '2023-10-01');
INSERT INTO books (title, series_id, publication_date) VALUES ('Tress of the Emerald Sea', 4, '2023-01-01');
INSERT INTO books (title, series_id, publication_date) VALUES ('Warbreaker', 4, '2009-06-09');
INSERT INTO books (title, series_id, publication_date) VALUES ('White Sand', 4, '2022-02-01');
INSERT INTO books (title, series_id, publication_date) VALUES ('Yumi and the Nightmare Painter', 4, '2023-07-01');
INSERT INTO books (title, series_id, publication_date) VALUES ('The Hope of Elantris', 4, '2006-01-01');
INSERT INTO books (title, series_id, publication_date) VALUES ("The Emperor's Soul", 4, '2012-11-01');
INSERT INTO books (title, series_id, publication_date) VALUES ('Shadows for Silence in the Forests of Hell', 4, '2013-12-03');
INSERT INTO books (title, series_id, publication_date) VALUES ('Sixth of the Dusk', 4, '2014-06-30');

SELECT * FROM books;