INSERT INTO character_magic_abilities VALUES (9, 10, 'Bondsmith');
INSERT INTO character_magic_abilities VALUES (10, 10, 'Cryptic - Lightweaving Spren');
INSERT INTO character_magic_abilities VALUES (11, 11, 'Unkown');
INSERT INTO character_magic_abilities VALUES (21, 10, 'Enlightened Mistspren - Truthwatcher Spren');
INSERT INTO character_magic_abilities VALUES (22, 10, 'Edgedancer');
INSERT INTO character_magic_abilities VALUES (23, 10, 'Skybreaker');
INSERT INTO character_magic_abilities VALUES (26, 10, 'Inkspren - Elsecaller Spren');
INSERT INTO character_magic_abilities VALUES (27, 10, 'Elsecaller');
INSERT INTO character_magic_abilities VALUES (30, 10, 'Windrunner');
INSERT INTO character_magic_abilities VALUES (32, 11, 'Heavenly One');
INSERT INTO character_magic_abilities VALUES (33, 10, 'Windrunner');
INSERT INTO character_magic_abilities VALUES (34, 10, 'Edgedancer');
INSERT INTO character_magic_abilities VALUES (37, 10, 'Windrunner');
INSERT INTO character_magic_abilities VALUES (38, 10, 'Windspren - Windrunner Spren');
INSERT INTO character_magic_abilities VALUES (42, 10, "Bearer of Jezrien's Honorblade, giving him power over the surges of gravitation and adhesion");
INSERT INTO character_magic_abilities VALUES (43, 10, 'Enlightened Lightweaver');
INSERT INTO character_magic_abilities VALUES (44, 10, 'Bondsmith');
INSERT INTO character_magic_abilities VALUES (48, 10, 'Cryptic - Lightweaving Spren');
INSERT INTO character_magic_abilities VALUES (49, 11, 'Altered One');
INSERT INTO character_magic_abilities VALUES (50, 10, 'Lightweaver');
INSERT INTO character_magic_abilities VALUES (51, 10, 'Enlightened Truthwatcher');
INSERT INTO character_magic_abilities VALUES (52, 10, 'Enlightened Truthwatcher');
INSERT INTO character_magic_abilities VALUES (55, 10, 'Lightweaver');
INSERT INTO character_magic_abilities VALUES (56, 10, 'Bondsmith Spren');
INSERT INTO character_magic_abilities VALUES (57, 10, 'Windrunner, later holder of a dawnshard');
INSERT INTO character_magic_abilities VALUES (58, 11, 'One of the Unmade');
INSERT INTO character_magic_abilities VALUES (4, 11, 'One of the Unmade');
INSERT INTO character_magic_abilities VALUES (59, 10, 'Windrunner');
INSERT INTO character_magic_abilities VALUES (60, 10, 'Bondsmith Spren');
INSERT INTO character_magic_abilities VALUES (61, 10, 'Windspren - Windrunner Spren');
INSERT INTO character_magic_abilities VALUES (62, 10, "Bearer of Jezrien's Honorblade, then Skybreaker");
INSERT INTO character_magic_abilities VALUES (62, 3, "Bearer of Nightblood");
INSERT INTO character_magic_abilities VALUES (64, 10, 'Windrunner');
INSERT INTO character_magic_abilities VALUES (65, 10, 'Cryptic Deadeye - Lightweaver Spren');
INSERT INTO character_magic_abilities VALUES (66, 10, 'Reacher - Willshaper Spren');
INSERT INTO character_magic_abilities VALUES (68, 10, 'Windspren - Windrunner Spren');
INSERT INTO character_magic_abilities VALUES (70, 10, 'Cultivationspren - Edgedancer Spren');
INSERT INTO character_magic_abilities VALUES (73, 1, 'Copper Misting (Smoker)');
INSERT INTO character_magic_abilities VALUES (76, 1, 'Pewter Misting (Thug)');
INSERT INTO character_magic_abilities VALUES (75, 1, 'Mistborn');
INSERT INTO character_magic_abilities VALUES (77, 1, 'Mistborn');
INSERT INTO character_magic_abilities VALUES (79, 1, 'Cadmium Misting (Pulser)');
INSERT INTO character_magic_abilities VALUES (80, 1, 'Bronze Misting (Seeker)');
INSERT INTO character_magic_abilities VALUES (80, 7, 'Inquisitor');
INSERT INTO character_magic_abilities VALUES (81, 7, 'Kandra');
INSERT INTO character_magic_abilities VALUES (82, 7, 'Kandra');
INSERT INTO character_magic_abilities VALUES (84, 1, 'Mistborn');
INSERT INTO character_magic_abilities VALUES (84, 5, 'Full Feruchemist');
INSERT INTO character_magic_abilities VALUES (84, 7, 'Some hemalurgic spikes');
INSERT INTO character_magic_abilities VALUES (85, 5, 'Full Feruchemist');
INSERT INTO character_magic_abilities VALUES (86, 1, 'Mistborn');
INSERT INTO character_magic_abilities VALUES (87, 1, 'Tin Misting (Tineye), then Mistborn');
INSERT INTO character_magic_abilities VALUES (89, 1, 'Tin Misting (Tineye)');
INSERT INTO character_magic_abilities VALUES (90, 7, 'Kandra');
INSERT INTO character_magic_abilities VALUES (91, 5, 'Full Feruchemist');
INSERT INTO character_magic_abilities VALUES (92, 1, 'Mistborn');
INSERT INTO character_magic_abilities VALUES (93, 1, 'Steel Misting (Coinshot)');
INSERT INTO character_magic_abilities VALUES (93, 5, 'Iron Ferring (Skimmer)');
INSERT INTO character_magic_abilities VALUES (94, 1, 'Bendalloy Misting (Slider)');
INSERT INTO character_magic_abilities VALUES (94, 5, 'Gold Ferring (Bloodmaker)');
INSERT INTO character_magic_abilities VALUES (95, 1, 'Mistborn');
INSERT INTO character_magic_abilities VALUES (97, 2, 'Elantrian');
INSERT INTO character_magic_abilities VALUES (100, 2, 'Elantrian');
INSERT INTO character_magic_abilities VALUES (102, 6, 'One of the Best Forgers Alive');
INSERT INTO character_magic_abilities VALUES (106, 8, 'Ancient Navigator');
INSERT INTO character_magic_abilities VALUES (107, 8, 'Navigator');
INSERT INTO character_magic_abilities VALUES (110, 3, 'Returned');
INSERT INTO character_magic_abilities VALUES (111, 3, 'Awakened sword');
INSERT INTO character_magic_abilities VALUES (112, 3, 'Returned');
INSERT INTO character_magic_abilities VALUES (113, 3, 'Returned');
INSERT INTO character_magic_abilities VALUES (115, 3, 'Awakener');
INSERT INTO character_magic_abilities VALUES (116, 3, 'Awakener');
INSERT INTO character_magic_abilities VALUES (117, 3, 'Awakener');
INSERT INTO character_magic_abilities VALUES (118, 3, 'Awakener');
INSERT INTO character_magic_abilities VALUES (120, 9, 'Sand Master');
INSERT INTO character_magic_abilities VALUES (121, 12, NULL);
INSERT INTO character_magic_abilities VALUES (121, 10, 'Lightweaving');
INSERT INTO character_magic_abilities VALUES (121, 1, 'Mistborn');
INSERT INTO character_magic_abilities VALUES (121, 3, 'Awakener');
INSERT INTO character_magic_abilities VALUES (121, 2, 'Elantrian');
INSERT INTO character_magic_abilities VALUES (121, 9, 'Sand Master');
INSERT INTO character_magic_abilities VALUES (122, 3, 'Awakener');
INSERT INTO character_magic_abilities VALUES (137, 13, NULL);
INSERT INTO character_magic_abilities VALUES (138, 14, NULL);
INSERT INTO character_magic_abilities VALUES (139, 14, NULL);
INSERT INTO character_magic_abilities VALUES (140, 14, NULL);